### ISSUE TITLE
How can I retrieve the likes count?

### ISSUE THREAD

**Issue by Sandgrouse** [PierreLebedel/KodexPostsLikes#3]
Hello,

I want to retrieve the total number of likes or dislikes in a post and use that value to provide some additional functionality in my wordpress theme. How can I achieve this?

Thanks

**Comment by PierreLebedel** [comment]
Hi!
You can use shortcode [kodex_post_like_count] to retrieve the number value.
Or to do what you want in PHP, you can load the post_meta `kodex_post_likes` and `kodex_post_dislikes` to find the array of votes, and do a `count()` to get the value.
