### ISSUE TITLE
You do not have sufficient permissions to access this page.

### ISSUE THREAD

**Issue by guztavoalves** [PierreLebedel/KodexPostsLikes#4]
Hello,
in my Wordpress, with guest session, I receive that error:
You do not have sufficient permissions to access this page.

When admin logged, it work normal.

What happen?

**Comment by PierreLebedel** [comment]
Hi, sorry for the delay (wow 6 years!)
I can't reproduce this issue on my end.
Fell free to reopen an issue if the problem is still current on your side.
